server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id : carAModule
          uri: http://localhost:8081/
          predicates:
            - Path=/cara/**
        - id: carBModule
          uri: http://localhost:8082/
          predicates:
            - Path=/carb/**
